name: RC Check
description: A workflow to check for rc packages
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
runs:
  using: 'docker'
  image: 'Dockerfile'
